### ISSUE TITLE
Result Summary "Pill" Out of Date.

### ISSUE THREAD

**Issue by vattay** [vattay/WuF#1]
Occasionally, the result pill install count is inaccurate. May show 0 when in fact some updates were installed.

**Comment by joshg678** [comment]
I have also experienced this issue.

**Comment by vattay** [comment]
Somewhat fixed in [8b3eacdf37]. It appears the IUpdate::isInstalled field does not update when the update is installed. The workaround I implemented runs a second search after an install operation. Thus a s0-d0-i0 pil represents a completely updated computer.
