### ISSUE TITLE
Unable to do multiple groups at once

### ISSUE THREAD

**Issue by joshg678** [vattay/WuF#3]
I would like to be able to run multiple groups at once.
Say i have Group1.txt, Group2.txt, and Group3.txt and i would like to do a Global Scan after i approved a bunch of updates, i have to run the command three different times and wait for all servers to get the scrips and start running before i can run the next group.

**Comment by vattay** [comment]
I think it makes sense to keep it with one input file. However, I can recommend:

`copy /b Group1.txt+Group2.txt+Group3.txt GroupMerge.txt`
