### ISSUE TITLE
Install Fails for IE8

### ISSUE THREAD

**Issue by vattay** [vattay/WuF#7]
Not sure why. The return code for the update is "Failed" but need to get reason.

**Comment by vattay** [comment]
The WindowsUpdate.log file shows that an error 0x80242004 is being reported during the IE 8 install. Translates to : SUS_E_UH_DOESNOTSUPPORTACTION  The update does not support the current action (install or uninstall).

I'm guessing IE installs can't be automated? Will need more research.

**Comment by joshg678** [comment]
I would think there is a way to automate it, but not through automatic updates because it requires you to choose a bunch of options.

**Comment by vattay** [comment]
Don't think this can be solved here.
